# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "search_do"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["MOROHASHI Kyosuke", "Michael Grosser"]
  s.date = "2011-12-24"
  s.email = "moronatural@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "TESTING",
    "VERSION",
    "examples/he_search.rb",
    "examples/person.rb",
    "init.rb",
    "lib/estraier_admin.rb",
    "lib/search_do.rb",
    "lib/search_do/backends.rb",
    "lib/search_do/backends/hyper_estraier.rb",
    "lib/search_do/backends/hyper_estraier/estraier_pure_extention.rb",
    "lib/search_do/dirty_tracking.rb",
    "lib/search_do/indexer.rb",
    "lib/search_do/utils.rb",
    "lib/vendor/estraierpure.rb",
    "lib/vendor/overview",
    "recipes/mode_maintenance.rb",
    "search_do.gemspec",
    "spec/backends/hyper_estraier_spec.rb",
    "spec/backends/result_document_spec.rb",
    "spec/dirty_tracking/bridge_spec.rb",
    "spec/estraier_admin_spec.rb",
    "spec/fixtures/stories.yml",
    "spec/indexer_spec.rb",
    "spec/search_do_spec.rb",
    "spec/setup_test_model.rb",
    "spec/spec_helper.rb",
    "tasks/acts_as_searchable_tasks.rake"
  ]
  s.homepage = "http://github.com/grosser/search_do"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "AR: Hyperestraier integration"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

